### ISSUE TITLE
Crash when reservation is made for first time

### ISSUE THREAD

**Issue by javier96** [adanvillarreal/Expediciones_biosfera#45]

**Comment by emiliogzzguerra** [comment]
After having had that problem I also found out that it crashes when the user already has reservations in the database but only in the following flow: 
1. User opens drawer menu
2. User clicks on "reservaciones"
3. User opens drawer menu
4. User clicks on "paquetes"
5. User clicks on any package
6. User clicks on "Solicitar disponibilidad"
7. User clicks on "Generar reservacion"

I think alternative flows in which the reservations list is displayed the app might also crash.
